import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  const spaces_name = new Array<string>(10);
  for (let i = 0; i < spaces_name.length; i++) {
    spaces_name[i] = `Space${i}`;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {spaces_name.map((value) => (
            <li key={value}>
              <Link href={`/space/${value}`}>
                <a>
                  <Image
                    src={`/images/space/${value}`}
                    alt={value}
                    width={100}
                    height={100}
                  />
                </a>
              </Link>
            </li>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
